import assert from 'node:assert/strict';
import test from 'node:test';
import { buildHostPlantGuideConfigs } from '../scripts/generate-host-plant-guides.mjs';

test('buildHostPlantGuideConfigs adds concrete data-backed host plant guides', () => {
  const manualConfigs = [
    {
      slug: 'sakura',
      name: 'サクラ',
      variants: ['サクラ', 'サクラ類'],
      searchPhrases: ['サクラにつく虫'],
    },
  ];
  const dataset = {
    hostPlants: {
      サクラ: ['m1', 'm2', 'm3', 'm4', 'm5', 'm6', 'm7'],
      アカザ: ['m1', 'm2', 'm3', 'm4', 'm5', 'm6'],
      ハリエンジュ: ['m1', 'm2', 'm3', 'm4', 'm5', 'm6'],
      地衣類: ['m1', 'm2', 'm3', 'm4', 'm5', 'm6', 'm7'],
      ヤナギ類: ['m1', 'm2', 'm3', 'm4', 'm5', 'm6', 'm7'],
      薄い植物: ['m1', 'm2', 'm3', 'm4', 'm5'],
    },
    plantDetails: {
      アカザ: {
        familyName: 'ヒユ科',
        scientificName: 'Chenopodium album var. centrorubrum',
        aliases: ['アカザ', 'アカザ類'],
      },
      ハリエンジュ: {
        familyName: 'マメ科',
        scientificName: 'Robinia pseudoacacia',
        aliases: ['ハリエンジュ'],
      },
      地衣類: {
        familyName: '地衣類',
        scientificName: 'Lichenes',
      },
      ヤナギ類: {
        familyName: 'ヤナギ科',
      },
      薄い植物: {
        familyName: 'テスト科',
        scientificName: 'Testus tenuis',
      },
    },
  };

  const configs = buildHostPlantGuideConfigs(dataset, { manualConfigs, target: 5 });
  const autoConfigs = configs.filter((guide) => guide.autoGenerated);

  assert.deepEqual(autoConfigs.map((guide) => guide.name), ['アカザ', 'ハリエンジュ']);
  assert.deepEqual(autoConfigs.map((guide) => guide.slug), [
    'chenopodium-album-var-centrorubrum',
    'robinia-pseudoacacia',
  ]);
  assert.equal(autoConfigs[0].variants.includes('アカザ類'), false);
  assert.equal(autoConfigs.some((guide) => guide.name === 'サクラ'), false);
});
