// Shared mapping between Japanese common names and the actual insect image basenames.
// Values intentionally match keys in public/image_extensions.json so downstream lookup works.
export const globalJapaneseToScientificMapping = new Map([
  ['ウスムラサキケンモン', 'Acronicta_subpurpurea'],
  ['オオマエベニトガリバ', 'Tethea_consimilis'],
  ['ショウブオオヨトウ', 'Helotropha_leucostigma'],
  ['シラオビキリガ', 'Cosmia_camptostigma'],
  ['シラホシキリガ', 'Cosmia_pyralina'],
  ['タカオキリガ', 'Pseudopanolis_takao'],
  ['ツマベニヒメハマキ', 'Phaecasiophora_roseana'],
  ['ナシキリガ', 'Cosmia_restituta'],
  ['ニッコウケンモン', 'Craniophora_praeclara'],
  ['ニッコウシャチホコ', 'Shachia_circumscripta'],
  ['ノコメセダカヨトウ', 'Orthogonia_sera'],
  ['ハスモンヨトウ', 'Spodoptera_litura'],
  ['マエジロシャチホコ', 'Notodonta_albicosta'],
  ['クロハナコヤガ', 'Aventiola_pusilla'],
  ['フタスジエグリアツバ', 'Gonepatica_opalina'],
  ['クロモクメヨトウ', 'Dypterygia_caliginosa'],
  ['コスジシロエダシャク', 'Cabera_purus'],
  ['シマフコヤガ', 'Corgatha_nitens'],
  ['シロテンツマキリアツバ', 'Amphitrogia_amphidecta'],
  ['スジモンヒトリ', 'Spilarctia_seriatopunctata'],
  ['プライヤエグリシャチホコ', 'Lophontosia_pryeri'],
  ['ベニスズメ', 'Deilephila_elpenor'],
  ['ヒメスズメ', 'Deilephila_askoldensis'],
  ['マダラキボシキリガ', 'Dimorphicosmia_variegata'],
  ['ナシイラガ', 'Narosoideus_flavidorsalis'],
  ['ヨモギオオホソハマキ', 'Phtheochroides_clandestina'],
  ['ノコメキシタバ', 'Catocala_bella'],
  ['ハマオモトヨトウ', 'Brithys_crini'],
  ['アオマダラタマムシ', 'Nipponobuprestis_amabilis'],
  ['ミヤマナカボソタマムシ', 'Coraebus_daisenensis'],
  ['オカモトトゲエダシャク', 'Apochima juglansiaria (Graeser, 1889)'],
  ['ルイスヒラタチビタマムシ', 'Habroloma_lewisii'],
  // --- Frequently accessed top-page species ---
  ['アオスジアゲハ', 'Graphium_sarpedon'],
  ['アオバシャチホコ', 'Zaranga_permagna'],
  ['ルリモンジャノメ', 'Elymnias hypermnestra hainana'],
  ['クロマダラソテツシジミ', 'Chilades_pandava'],
  ['オオチャバネセセリ', 'Polytremis_pellucida'],
  ['ムラサキシジミ', 'Narathura japonica'],
  ['ウスクロスジツトガ', 'Chrysoteuchia diplogramma Zeller'],
  ['ゴマダラキリガ', 'Conistra castaneofasciata Motschulsky'],
  ['イシガケチョウ', 'Cyrestis thyodamas'],
  ['ヤエヤマコブヒゲアツバ', 'Zanclognatha yaeyamalis Owada'],
  ['ヤエヤマカラスアゲハ', 'Papilio bianor okinawensis'],
  ['クロスジツトガ', 'Flavocrambus striatellus Leech'],
  ['シロスジツトガ', 'Crambus argyrophorus Butler'],
  ['シンジュサン', 'Samia cynthia (Drury, [1773])'],
  ['アマギシャチホコ', 'Eriodonta amagisana Marumo'],
  ['アマヒトリ北海道亜種', 'Phragmatobia amurensis amurensis Seitz, 1910'],
  ['アカモクメヨトウ', 'Apamea aquila Donzel, 1837'],
  ['ギンボシスズメ', 'Parum colligata Walker'],
  ['イボタケンモン', 'Craniophora ligustri'],
  ['キボシミスジトガリバ本州亜種', 'Achlya longipennis longipennis Inoue'],
  ['クロスジコブガ', 'Meganola_fumosa'],
  ['ウスベリケンモン', 'Anacronicta nitida Butler'],
  ['カバイロキバガ', 'Dichomeris heriguronis Matsumura'],
  ['オオバトガリバ', 'Tethea ampliata ampliata Butler'],
  ['カクモンキシタバ', 'Chrysorithrum amatum Bremer & Grey'],
  ['アトヘリヒトホシアツバ', 'Hemipsectra fallax Butler'],
  ['カギバアオシャク', 'Tanaorhinus reciprocata confuciaria Walker'],
  ['アカハラゴマダラヒトリ', 'Spilosoma punctarium Stoll'],
  ['カクバネヒゲナガキバガ', 'Lecitholaxa thiodora Meyrick'],
  ['クビワウスグロホソバ', 'Macrobrochis staudingeri staudingeri Alphéraky'],
  ['ウスイロオオエダシャク', 'Amraica superans superans Butler'],
  ['キマダラアツバ', 'Lophomilia polybapta Butler'],
  ['ツマモンキリガ', 'Imosca_coreana'],
  ['ツマオビアツバ', 'Zanclognatha griselda Butler'],
  ['クスサン', 'Saturnia japonica (Moore, 1872)'],
  ['スカシエダシャク', 'Krananda semihyalina Moore, 1868'],
  ['マエホシヨトウ', 'Pyrrhidivalva_sordida'],
  ['マルモンキノコヨトウ', 'Bryomoia_melachlora'],
  ['アカスジキヨトウ', 'Mythimna_postica'],
  ['ウスイロキヨトウ', 'Mythimna_inanis'],
  ['ウスクロモクメヨトウ', 'Dipterygina_cupreotincta'],
  ['アオモンギンセダカモクメ', 'Cucullia_argentea'],
  ['ヤクシマキリガ', 'Mesorhynchaglaea pacifica Sugi, 1980'],
  ['アカキリバ', 'Gonitis_mesogona'],
  ['アオバシャチホコ', 'Zaranga_permagna'],
  ['アオスジアゲハ', 'Graphium_sarpedon']
]);

export const getMappedScientificFilename = (japaneseName) => {
  if (!japaneseName) return undefined;
  return globalJapaneseToScientificMapping.get(japaneseName.trim());
};
